require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = { enable = true },
  ensure_installed = {
    'lua',
    'luadoc',
    'luap',
    'vim',
    'vimdoc',
    'bash',
    'diff',
    'html',
    'css',
    'scss',
    'powershell',
    'javascript',
    'typescript',
    'tsx',
    'regex',
    'jsdoc',
    'json',
    'jsonc',
    'query',
    'git_rebase',
    'gitcommit',
    'git_config',
    'markdown',
    'markdown_inline',
    'toml',
    'xml',
    'yaml',
  },
  auto_install = true,
  textobjects = {
    move = {
      enable = true,
      set_jumps = true,
      goto_next_start = { [']f'] = '@function.outer', [']c'] = '@class.outer', [']a'] = '@parameter.inner' },
      goto_next_end = { [']F'] = '@function.outer', [']C'] = '@class.outer', [']A'] = '@parameter.inner' },
      goto_previous_start = { ['[f'] = '@function.outer', ['[c'] = '@class.outer', ['[a'] = '@parameter.inner' },
      goto_previous_end = { ['[F'] = '@function.outer', ['[C'] = '@class.outer', ['[A'] = '@parameter.inner' },
    },
  },
})

require('treesitter-context').setup()
